generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StoryType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          story_type
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [ id, =type ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
